config/routes.rb
Rails.application.routes.draw do
    get 'todos', to: 'todos#index'
    get 'todos/new' #ruta metodo new 
    post 'todos', to: 'todos#create' #ruta metodo create
    get 'todos/:id', to: 'todos#show', as: 'todo'
    get 'todos/:id/edit', to: 'todos#edit', as: 'edit'
    patch 'todos/:id', to: 'todos#update'
    delete 'todos/:id', to: 'todos#destroy'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
      @todos = Todo.all  #devuelve todos los elementos
    end

    def new
      @todo = Todo.new # @todo almacena nueva instancia de Todo  
    end

    def create
      @todo = Todo.new(todo_params)
      @todo.save
      redirect_to todos_path  
    end

    def show
       @todo = Todo.find(params[:id]) #busca un todo en base a params id, se asigna a @todo 
    end

    def edit
       @todo = Todo.find(params[:id]) 
    end

    def update
       @todo = Todo.find(params[:id])
       @todo.update(todo_params)
       redirect_to todos_path 
    end

    def destroy
       @todo = Todo.find(params[:id])
       @todo.destroy
       redirect_to todos_path 
    end

    def complete
       @todo = Todo.find(params[:id])
       @todo.completed = true
       @todo.save
       redirect_to todos_path 
    end

    def list
      @todos = Todo.all
      
    end


    private
    def todo_params
       params.require(:todo).permit(:description, :completed) 
    end


    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>
  <%= f.label :description, "Nombre Formulario" %>
  <%= f.text_field :description %>
  <%= f.check_box :completed %>

  <%= f.submit "Crear ToDo" %>

    
<% end %>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<% @todos.each do |todo| %>
    
    <ul>
        <div class="well">
            <li> <h1> <%= link_to todo.description, todo %> </h1> </li>
            

            <li> <%= todo.completed %> </li>
            <li> <%= link_to "Edit", edit_path(todo) %> </li>
            <li> <%= link_to "Destroy", todo, method: :delete %> </li>
            
       </div>
    </ul>
<% end %>

<h1> <%= link_to "Crear ToDo", todos_new_path %> </h1>

app/views/todos/list.html.erb
<div class="container">
    <div class="col-md-6">
    </div> 

    <div class="col-md-6">
    </div>










</div>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<h1> Todo Form app </h1>
<h1> <%= @todo.description %> </h1>
<p> <%= @todo.completed %> </p>